xh/toolbox

client-app/src/desktop/tabs/containers/TabPanelContainerPanel.js
Fixed some errors when switching between tabs in the tab container example panel from the recent model changes 
Added example for the new tab state properties
=> TabContainer example fixes

client-app/src/desktop/tabs/charts/LineChartModel.js, client-app/src/desktop/tabs/examples/portfolio/LineChartModel.js, client-app/src/desktop/tabs/examples/portfolio/OHLCChartModel.js, client-app/yarn.lock
Goes with hoist-react PR: https://github.com/exhi/hoist-react/pull/885, 
in which:
highcharts was updated to v7.0.1
exporting was fixed
=> Enabled exporting in several charts.

client-app/src/desktop/App.scss, client-app/src/desktop/common/SampleGrid.js
+ Using the new `containerRef` param with `XH.Toast()` to show the existing demo toasts anchored within the grid.
=> Example for anchored toast in SampleGrid

client-app/src/core/svc/PortfolioService.js, client-app/src/desktop/tabs/examples/portfolio/OrdersPanel.js, client-app/src/desktop/tabs/grids/cube/CubeDataModel.js, client-app/src/mobile/treegrids/TreeGridPageModel.js
+ Use non-blocking whileAsync() util within PortfolioService to generate orders/ref data while allowing UI renders to continue.
+ Remove prior workarounds with one-off delays in service methods.
=> Improvements to portfolio and cube examples

client-app/src/desktop/common/GridStyleSwitches.js, client-app/src/desktop/tabs/grids/StandardGridPanel.js
See related **Hoist** Issue [#1041](https://github.com/exhi/hoist-react/issues/1041)
=> Update Toolbox to show off new GridModel.cellBorders

client-app/src/core/svc/PortfolioService.js, client-app/src/core/svc/TradeService.js, client-app/src/desktop/common/SampleGrid.js, client-app/src/desktop/common/SampleTreeGrid.js, client-app/src/desktop/tabs/grids/cube/CubeDataModel.js, client-app/src/mobile/treegrids/TreeGridPageModel.js
Examples for https://github.com/exhi/hoist-react/pull/1142
Added bottom-pinned summary row for the simple grid example.
Added select to the Tree Grid example to choose location of summary row (top, bottom, none)
For cube example, summary row is configured to appear at the top (only visible when including a root node)
=> Examples of Grid summary row

client-app/src/examples/portfolio/GridPanelModel.js, client-app/src/examples/portfolio/MapPanelModel.js, client-app/src/examples/portfolio/ui/ef/GridPanel.js, client-app/src/examples/portfolio/ui/ef/MapPanel.js, client-app/src/examples/portfolio/ui/jsx/GridPanel.js, client-app/src/examples/portfolio/ui/jsx/MapPanel.js, grails-app/init/io/xh/toolbox/BootStrap.groovy
The tree in the Portfolio example app will now be expanded by default and will display a more interesting grouping.
Will fix issue https://github.com/xh/toolbox/issues/247
=> Portfolio defaults

grails-app/init/io/xh/toolbox/BootStrap.groovy, grails-app/services/io/xh/toolbox/MonitorDefinitionService.groovy, grails-app/services/io/xh/toolbox/app/NewsService.groovy, grails-app/services/io/xh/toolbox/app/RecallsService.groovy, src/main/groovy/io/xh/toolbox/portfolio/PortfolioDataSet.groovy
Adds several new monitors to toolbox, including storage space used, presence of any "malicious files" (i.e. files with names containing .sh or .exe), status of connection to FDA website, and server memory usage.
Also corrects a few edge cases in the existing monitors where they could behave unexpectedly if the server has not yet fetched any news stories.
Implements new monitors per https://github.com/xh/toolbox/issues/244
=> New monitors

client-app/src/examples/news/App.js, grails-app/init/io/xh/toolbox/BootStrap.groovy, grails-app/services/io/xh/toolbox/app/NewsService.groovy
This is meant to solve this issue:
https://github.com/xh/toolbox/issues/228
I reduce load on the NewsAPI two ways:
1. Use the v2 api to fetch from all sources with one request.
https://newsapi.org/docs/v2-migration#multiple-sources
2. ~~Add in a five-minute delay before we fetch news for the first time, which should reduce load from development machines where we frequently restart the server.~~
3. Make the NewsService start fetching lazily. It will still fetch news stories every hour, but it only starts fetching once someone actually accesses the NewsService (either by viewing the page or by running the monitors). This makes the startup delay irrelevant, so I removed the delay.
=> Reduce news load

client-app/src/desktop/common/SampleGridModel.js
This goes along with this change:
https://github.com/xh/hoist-react/pull/1484
It isn't sensible to export the dynamic headerName here, so we set it manually.
=> Add exportName to company column

client-app/src/examples/news/NewsPanelModel.js
Use XH.genId to ensure all news items will have a unique ID
=> Switch idSpec

client-app/src/mobile/treegrids/TreeGridDetailPage.js
The TreeGridDetailPage was changed to refer to `record.data.mktVal` rather than `record.mktVal` as part of https://github.com/xh/toolbox/pull/277.
However, this was unnecessary because the TreeGridDetailPage reads data directly from the server, not from a store, so it does not need to use the new Store API.
=> Undo change from record API update

client-app/src/desktop/common/grid/SampleTreeGridModel.js
`allDescendants` already includes the parent. Therefore, we do not need to explicitly update `rec`; updating `allDescendants` will catch `rec` at the same time.
We also made an incorrect call to modifyRecords. It expects to receive an object with the ID to upgrade.
=> Remove duplicate updates

client-app/src/admin/AppModel.js, client-app/src/admin/roadmap/PhaseRestPanel.js, client-app/src/admin/roadmap/ProjectRestPanel.js, client-app/src/admin/roadmap/RoadmapTab.js, client-app/src/desktop/tabs/home/HomeTab.scss, client-app/src/desktop/tabs/home/roadmap/RoadmapModel.js, client-app/src/desktop/tabs/home/roadmap/RoadmapView.js, client-app/src/desktop/tabs/home/roadmap/RoadmapView.scss, client-app/src/desktop/tabs/home/roadmap/RoadmapViewItem.js, grails-app/domain/io/xh/toolbox/roadmap/Project.groovy
This PR addresses most of follow-up Roadmap issues in https://github.com/xh/toolbox/issues/361
- Changed way description truncates and popover appears on hover over [...] element
- Title char limit increased to 100 but truncates at 55, conditionally rendering a popover if exceeds length.
- Added line breaks to popover description, not in dataView display.
- Fixed Category constraint - can now add new category. Still need to specify icon in roadmapCategories config, else defaults to experiment (flask) icon.
- Changed widths of Welcome and Roadmap panels on home tab
- Reordered top level tabs in Admin
- Increased size of textArea in REST editor for Project description
- Github Links should now be entered as new lines instead of comma separated
Upcoming/released filtering and phase …
=> Roadmap fixes

client-app/src/examples/news/NewsPanelItem.js
Previously, a news item was an hbox. This lead to problems where not all news items had the same width. Switching the news-item to an hframe solves this.
Problem:
After fix:
=> Switch to hframe to fix alignment

client-app/src/desktop/tabs/containers/DockContainerPanel.js
DockContainer example defers to DockContainer's managed refresh to refresh grid.
See hoist-react PR: https://github.com/xh/hoist-react/pull/1753
=> DockContainer Render Mode / Refresh Mode

client-app/src/mobile/App.scss, client-app/src/mobile/AppModel.js, client-app/src/mobile/containers/ContainersPage.js, client-app/src/mobile/containers/HBoxPage.js, client-app/src/mobile/containers/ToolbarPage.js, client-app/src/mobile/containers/VBoxPage.js, client-app/src/mobile/dataview/DataViewPage.js, client-app/src/mobile/form/FormPage.js, client-app/src/mobile/grids/GridDetailPage.js, client-app/src/mobile/grids/GridPage.js, client-app/src/mobile/home/HomePage.js, client-app/src/mobile/icons/IconPage.js, client-app/src/mobile/panels/PanelPage.js, client-app/src/mobile/panels/PanelsPage.js, client-app/src/mobile/panels/ScrollablePanelPage.js, client-app/src/mobile/pinPad/PinPadPage.js, client-app/src/mobile/popups/PopupsPage.js, client-app/src/mobile/treegrids/TreeGridDetailPage.js, client-app/src/mobile/treegrids/TreeGridPage.js
+ NavigatorModel.routes > NavigatorModel.pages
+ NavigatorModel.pages > NavigatorModel.stack
+ NavigatorPageModel > PageModel
+ Removed `Page` from mobile toolkit. Navigator and TabContainer now wrap their content in an Onsen Page.
+ Fixed Toolbox 'Containers' page styling
See hoist-react PR: https://github.com/xh/hoist-react/pull/1732
=> Navigator refactor

client-app/src/admin/roadmap/ProjectRestPanel.js, client-app/src/desktop/tabs/home/roadmap/RoadmapModel.js, client-app/src/desktop/tabs/home/roadmap/RoadmapViewItem.js, grails-app/domain/io/xh/toolbox/roadmap/Project.groovy
This PR addresses https://github.com/xh/toolbox/issues/423.
- Sort projects by sorted phase groups, then project sort order in admin rest grid
- Change alphanumeric sort to integer sort in roadmap and rest grid
- Handle Github icon rendering based on number of links
=> Roadmap Improvements

client-app/src/admin/tests/grids/GridTestModel.js, client-app/src/desktop/common/grid/SampleTreeGridModel.js, client-app/src/desktop/tabs/grids/TreeGridPanel.js
See matching hoist-react PR
Tree grid example shows this optional icon; tree grid w/ checkbox example does not
=> Tree column header has expand/collapse all icon

client-app/src/mobile/charts/ChartPageModel.js
Add more features to mobile chart example to test interaction of dragging and swiping.
See hoist-react PR.
=> Disable swipe to refresh/go back on mobile charts to allow for dragging

CHANGELOG.md, build.gradle, grails-app/conf/runtime.groovy
+ Upgraded MySQL instances have better defaults re. character encoding (`utf8mb4` for proper unicode/emoji support), and in general we were due for an upgrade here.
+ Remove defaulted properties from JDBC URL, move `useSSL` flag to driver properties block along with the others.
=> MySQL driver and datasource properties updated to v8

client-app/src/desktop/common/grid/SampleGridModel.js
=> Restore SampleGridModel's groupBy select input when restoring grid defaults

CHANGELOG.md, grails-app/services/io/xh/toolbox/MonitorDefinitionService.groovy
Toolbox lacked any monitors with messages. 
One of them can be easily set to succeed / fail via the config as it returns a constant value, the other always throws an exception.
These can/should be disabled most of the time, but could be useful to have for testing monitor features.
=> Added two example monitors with a message to toolbox

CHANGELOG.md, client-app/src/desktop/tabs/grids/ColumnFilteringPanelModel.js
GridModel was missing a column definition for a field that was in the filterChooserModel and present in the data being loaded into the grid.
Motivated by having a boolean filterChooser field in testing of https://github.com/xh/hoist-react/pull/3149 .
=> Bug fix - `activeCol` was missing ColumnFilteringPanelModel's GridModel

client-app/src/desktop/common/grid/SampleColumnGroupsGrid.ts
The "Group rows" toggle switch on the grouped columns example grid was not bound to any property on the model. 
This PR adds a bindable property and reaction to toggle row grouping for this grid.
=> Create reaction for groupRows toggle on grouped columns grid panel

client-app/src/Bootstrap.ts
This is the new "declare" statement that I came up with, also added comments to hopefully explain our magic.
I ended up keeping the `interface` for XHApi because it will otherwise give `error TS2323: Cannot redeclare exported variable`.
The `XH` const re-declaration is annotated with `// @ts-ignore` as to not give the `error TS2323` like above, but IntelliJ is able to notice uses of service methods better due to it.
Without the XH line:
With the XH line:
=> Added new declare statement in Bootstrap.ts, for IntelliJ

client-app/src/admin/tests/Select/SelectTestPanel.ts
Issue: https://github.com/xh/hoist-react/issues/3366
PR: https://github.com/xh/hoist-react/pull/3367
The branch reduces width of the last select on the Select Test page in Admin, and has enableTooltipsOnTags: true on the select to demo tooltips on tags.
=> demo branch for Hoist React PR for new select.enableTooltipsOnTags prop

client-app/src/desktop/AppComponent.ts
allow the tab switcher to overflow at smaller screen widths, enabling users to access all tabs. The admin panel's switcher already has overflow enabled.
=> allow horizontal scrolling of the main tab switcher

client-app/src/desktop/tabs/home/widgets/roadmap/RoadmapModel.ts
In light of ![this change](https://github.com/xh/toolbox/commit/8868ca0e5a5fab5ba7b95e0968f63dd60daa2504), we identified `groupSortFn` as a first-class parameter for the `DataViewModel`. This PR reverts the call, thanks to the additional parameters introduced ![here](https://github.com/xh/hoist-react/compare/improved-DataViewModel-api)
=> pass groupSortFn directly to DataViewModel

grails-app/init/io/xh/toolbox/BootStrap.groovy
& Move jsLicenses config into ensureRequiredConfigsCreated
I run with H2, so the DB gets recreated every time.  Maybe that helped find this issue?
Without this fix, user.hasRole(..  in RoleAdminService.ensureUserHasRoles throws an NPE because there is no user.
and then this error shows up in the UI:
=> Move createLocalAdminUserIfNeeded to before services init

client-app/src/core/svc/PortfolioService.ts, client-app/src/examples/portfolio/detail/charts/LineChart.ts, client-app/src/examples/portfolio/detail/charts/OHLCChart.ts, grails-app/controllers/io/xh/toolbox/portfolio/PortfolioController.groovy
**Before:**
**After**
**Commit History:**
feature(portfolio-ex): added error handling to line chart panel when market data is null
feat(portfolio-ex): throw error from portfolio controller and render error message in chart panels
**Note:**
My first PR, just trying to get used to the workflow.
=> Implement Error Handling in LineChart Panel in Portfolio example.

client-app/src/desktop/AppModel.ts, client-app/src/desktop/tabs/other/OtherTab.ts, client-app/src/desktop/tabs/other/routing/SimpleRoutingPanel.tsx
This PR addresses the simple case of the following issue: https://github.com/xh/toolbox/issues/458. A video sample of the functionality working is shown below, along with a screenshot of the final appearance of the tab.
**Video:**
https://github.com/xh/toolbox/assets/163027616/ca767af9-3d72-41dc-9d40-84c6de2318ca
=> Simple Routing Panel in the "Other" tab

grails-app/services/io/xh/toolbox/security/AuthenticationService.groovy, grails-app/services/io/xh/toolbox/user/UserService.groovy
Companion to https://github.com/xh/hoist-core/pull/360
Toolbox's `UserService.groovy` is now allowed to use its own `User` type, rather than being forced to refer to User by `HoistUser`.
=> UserService methods can now return User rather than HoistUser

.env.template, .gitignore, README.md, build.gradle, gradle.properties
+ Install dotenv Gradle plugin to source env vars from a `.env` file for local development launches via `bootRun`.
+ Include `.env.template` (without any credentials).
+ Update README, including new instructions on wrapper project configuration.
=> Swap to env vars for local dev instance config

client-app/src/examples/news/NewsPanelItem.scss
The news page loads visually correct initially, but on scrolling items out then back onto screen we would see the content of an individual item overflow the parent.
**_Initial:_**
**_After scrolling out then back into view:_**
This is a side effect of the virtual pagination used by AG grid. Technically these items were already breaking out of their parent's container on load. We just dont see it because the items were stacked top to bottom in their containing DIV, and so each item's z-index was lower than the next item in the list, and said next item would cover the accidental overflow.
Once we start to scroll, AG grid starts shifting / pushing grid element into and out of the parent, and using translation CSS definitions to keep them visually positioned correct in the overall list. …
=> Stop news app items from overflowing their parent container

grails-app/services/io/xh/toolbox/admin/TestCacheService.groovy, grails-app/services/io/xh/toolbox/admin/TestCachedValueService.groovy
- 15s wait introduced by TestCacheService seems unfortunate for every local start of toolbox - disable both of these services by default, but provide instance config to allow a dev who wants to run them locally to keep them on.
=> Skip cache testing service inits in local dev by default

client-app/src/desktop/tabs/charts/LineChartModel.ts, client-app/src/desktop/tabs/charts/LineChartPanel.tsx, client-app/src/desktop/tabs/charts/OHLCChartModel.ts, client-app/src/desktop/tabs/charts/OHLCChartPanel.tsx, client-app/src/desktop/tabs/panels/BasicPanel.tsx, client-app/src/desktop/tabs/panels/BasicPanelModel.ts
Paired with this Hoist React PR: https://github.com/xh/hoist-react/pull/4005
=> Customized chart context menu on lineChart.
