xh/toolbox

- client-app/src/desktop/tabs/containers/HBoxContainerPanel.js
- client-app/src/desktop/tabs/containers/VBoxContainerPanel.js
'Fixes' Hoist React Issue #506 in terms of what malvina noticed. But the issue of making our vbox/hbox  flex in a more intuitive way is still yet to be solved.
> Remove padding from child elements for better flex demo

- grails-app/init/io/xh/toolbox/BootStrap.groovy
To test new filter by inactive feature in User Admin panel
> Create dummy inactive user

- grails-app/init/io/xh/toolbox/BootStrap.groovy
- grails-app/services/io/xh/toolbox/App/NewsService.groovy
- grails-app/services/io/xh/toolbox/MonitorDefinitionService.groovy
> News Feed Status Monitors

- client-app/src/mobile/form/FormPage.js
- client-app/src/mobile/form/FormPageModel.js
See hoist-react PR: https://github.com/exhi/hoist-react/pull/839
> Add ButtonGroup and ButtonGroupInput to mobile toolkit

- client-app/src/mobile/grids/GridPageModel.js
See https://github.com/exhi/hoist-react/pull/864
> MultiFieldRenderer returns DOM elements rather than React components

- client-app/src/desktop/tabs/forms/ControlsPanel.js
- client-app/src/desktop/tabs/forms/ControlsPanel.scss
- client-app/src/desktop/tabs/forms/ValidationPanel.js
- client-app/src/desktop/tabs/forms/ValidationPanelModel.js
- client-app/src/desktop/tabs/other/JsxPanel.js
See https://github.com/exhi/hoist-react/pull/943
> Rationalise sizing of HoistInputs and FormField

- client-app/src/desktop/tabs/forms/ControlsPanel.js
- client-app/src/desktop/tabs/forms/ValidationPanel.js
+ Adjust ValidationPanel component hierarchy to use flexbox effectively throughout.
> Tweak FormField sizing

- client-app/src/desktop/tabs/charts/LineChartModel.js
- client-app/src/desktop/tabs/charts/LineChartPanel.js
- client-app/src/desktop/tabs/charts/OLHCChartModel.js
- client-app/src/desktop/tabs/charts/OLHCChartPanel.js
This code should be tested with this [branch of hoist react.](https://github.com/exhi/hoist-react/tree/chartResize)
> Demonstrate new resizable and aspect ratio chart features.

- client-app/src/desktop/AppModel.js
- client-app/src/desktop/tabs/forms/FormsTab.js
- client-app/src/desktop/tabs/forms/ToolbarFormPanel.js
- client-app/src/desktop/tabs/forms/ToolbarFormPanelModel.js
- client-app/src/desktop/tabs/forms/ValidationPanelModel.js
Add an example page to test various inputs within toolbars.
> Ensure that Forms and FormFields are usable within Toolbars.

- client-app/src/desktop/common/SampleGrid.js
Companion to exhi/hoist-react#1070
> Example of gridModel.groupSortFn in SampleGrid

- client-app/src/desktop/tabs/grids/RestGridPanel.js
Bug Fix: Toolbox `REST Grid Panel` now exports appropriately.  Addresses issue #189
> `enableExport: true` fix

- client-app/src/desktop/tabs/other/FileChooserPanel.js
Toolbox -> Other -> FileChooser got 2 new toggles: `enableMulti` and `enableAddMulti`
> FileChooserPanel to show off `enableMulti` and `enableAddMulti`

- client-app/src/desktop/tabs/forms/ControlsPanel.js
- client-app/src/desktop/tabs/forms/ToolbarFormPanel.js
- client-app/src/desktop/tabs/forms/ValidationPanel.js
Adjust DateInput widths to account for new right icon
> Date input focus

- client-app/src/desktop/tabs/examples/portfolio/PositionsPanelModel.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
- grails-app/init/io/xh/toolbox/BootStrap.groovy
See https://github.com/exhi/hoist-react/issues/1233
> DimensionChooser persists both last value and history to preference

- grails-app/init/io/xh/toolbox/BootStrap.groovy
- src/main/groovy/io/xh/toolbox/NewsItem.groovy
+ For hoist-core 6.0 - see https://github.com/exhi/hoist-core/pull/82
> Update JSON serialization to Jackson

- client-app/src/mobile/containers/ToolbarPage.js
- client-app/src/mobile/containers/ToolbarPageModel.js
> Fix value binding to mobile toolbar select example.

- client-app/src/desktop/tabs/grids/DataViewPanel.js
- client-app/src/examples/news/NewsPanelModel.js
See https://github.com/exhi/hoist-react/issues/1337
> Add sortBy support to DataViewModel

- client-app/src/desktop/tabs/grids/DataViewPanel.js
- client-app/src/examples/news/NewsPanel.js
- client-app/src/examples/news/NewsPanelModel.js
- client-app/src/mobile/AppModel.js
- client-app/src/mobile/dataview/DataViewItem.js
- client-app/src/mobile/dataview/DataViewItem.scss
- client-app/src/mobile/dataview/DataViewPage.js
- client-app/src/mobile/dataview/DataViewPageModel.js
- client-app/src/mobile/home/HomePage.js
+ Add DataView example to mobile app
> Promote DataView to a cross-platform component

- client-app/src/desktop/common/SampleGridModel.js
PR: https://github.com/xh/hoist-react/pull/1379
> Submenus to test fix proposed in Hoist React PR #1379

- client-app/src/desktop/common/SampleTreeGridModel.js
Changes for https://github.com/xh/hoist-react/pull/1380
> Use new Record methods in Tree w/Checkbox example

- client-app/src/desktop/common/SampleTreeGridModel.js
Changes for https://github.com/xh/hoist-react/pull/1392
> Cleanup tree w/checkbox tree column renderer

- client-app/src/desktop/common/SampleColumnGroupsGrid.js
- client-app/src/desktop/common/SampleGridModel.js
+ Improvements to Toolbox's grouped column grid example to demo new functionality around dynamic column headers and make some other incremental fixes / improvements.
> Dynamic column header names

- client-app/src/desktop/AppModel.js
- client-app/src/desktop/tabs/charts/ChartsTab.js
- client-app/src/desktop/tabs/charts/OHLCChartPanel.js
Should fix this issue:
https://github.com/xh/toolbox/issues/293
> Rename all references to 'olhc'

- client-app/src/desktop/tabs/containers/DockContainerPanel.js
To fix https://github.com/xh/toolbox/issues/240
> Add SampleGridModel to DockContainerPanel

- client-app/src/desktop/common/SampleGridModel.js
To fix https://github.com/xh/toolbox/issues/297
> Correct 'undefined' in termination toast

- client-app/src/desktop/common/SampleColumnGroupsGrid.js
- client-app/src/desktop/common/SampleGridModel.js
- client-app/src/desktop/tabs/grids/DataViewPanel.js
This PR implements the new contextMenuItems prop that was added to Hoist React in PR
for issue https://github.com/xh/hoist-react/issues/1419.
> Use new contextMenu prop instead of contextMenuFn (hoist #1419)

- client-app/src/desktop/tabs/charts/LineChartModel.js
- client-app/src/desktop/tabs/charts/LineChartPanel.js
- client-app/src/desktop/tabs/charts/OHLCChartModel.js
- client-app/src/desktop/tabs/charts/OHLCChartPanel.js
- client-app/src/examples/portfolio/detail/ChartsPanel.js
- client-app/src/examples/portfolio/detail/LineChartModel.js
- client-app/src/examples/portfolio/detail/OHLCChartModel.js
Move `desktop/cmp/charts` > `cmp/charts`. 
See issue https://github.com/xh/hoist-react/issues/1463
> Make Chart & ChartModel cross-platform

- client-app/src/admin/tests/cube/CubeDataPanel.js
- client-app/src/admin/tests/grids/GridTestPanel.js
- client-app/src/desktop/common/SampleColumnGroupsGrid.js
- client-app/src/desktop/common/SampleGrid.js
- client-app/src/desktop/common/SampleTreeGrid.js
- client-app/src/desktop/tabs/grids/DataViewPanel.js
- client-app/src/examples/news/NewsPanel.js
- client-app/src/examples/portfolio/detail/OrdersPanel.js
- client-app/src/mobile/grids/GridPage.js
See issue https://github.com/xh/hoist-react/issues/1474
> Added StoreFilterField example to mobile

- client-app/src/desktop/common/SampleGridModel.js
Relates to this issue:
https://github.com/xh/hoist-react/issues/1483
> Add check that grid is ready before selecting row

- client-app/src/desktop/common/SampleGrid.scss
- client-app/src/desktop/common/SampleGridModel.js
Example for https://github.com/xh/hoist-react/pull/1485
> Add tooltip element renderer example to sample grid

- client-app/src/desktop/tabs/panels/PanelSizingPanel.js
- client-app/src/examples/portfolio/detail/DetailPanelModel.js
- client-app/yarn.lock
https://github.com/xh/hoist-react/pull/1499
> Updated example to demonstrate minSize and maxSize

- client-app/src/admin/AppModel.js
- client-app/src/admin/tests/TestsTab.js
- client-app/src/admin/tests/grids/GridTestPanel.js
New pull request to add a button to demonstrate EnsureSelectionVisible.
> Add button for testing scrollToSelection to GridTestPanel

- client-app/src/desktop/tabs/containers/dash/widgets/ButtonWidget.js
See https://github.com/xh/hoist-react/pull/1558
> Set Icon separately from view state

- client-app/src/admin/tests/Select/SelectTestPanel.js
- client-app/src/desktop/tabs/forms/InputsPanel.js
Tweaks to custom option renderers to account for changes to default select padding
https://github.com/xh/hoist-react/pull/1572
> Select option padding

- client-app/src/desktop/tabs/grids/DataViewPanel.js
- client-app/src/examples/news/NewsPanel.js
- client-app/src/examples/news/NewsPanelModel.js
- client-app/src/mobile/dataview/DataViewPage.js
- client-app/src/mobile/dataview/DataViewPageModel.js
We will actually want to merge this one.
> Move itemHeight to model

- client-app/src/desktop/AppModel.js
This PR incorporates changes made to TabContainerModel in Hoist-React PR https://github.com/xh/hoist-react/pull/1655
> AppModel's TabContainerModel uses new track config

- client-app/src/admin/tests/grids/GridTestModel.js
- client-app/src/examples/portfolio/detail/ChartsPanelModel.js
Added for consistency with changes made for #1680
> Use debounce rather than delay for MobX reactions

- client-app/src/admin/tests/fetch/FetchApiTestPanel.js
- client-app/src/desktop/tabs/forms/ToolbarFormPanel.js
- client-app/src/desktop/tabs/other/ClockPanel.js
- client-app/src/desktop/tabs/panels/ToolbarPanel.js
Issue: https://github.com/xh/hoist-react/issues/1524
Hoist-React PR: https://github.com/xh/hoist-react/pull/1719
> Update toolbars to work with overflow.

- client-app/src/examples/portfolio/detail/DetailPanelModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/1787
> Update to PanelModel api

- client-app/src/examples/portfolio/detail/DetailPanelModel.js
> Revert "Update to PanelModel api"

- client-app/src/desktop/tabs/containers/DockContainerPanel.js
See issue: https://github.com/xh/hoist-react/issues/1773
See hoist-react PR: https://github.com/xh/hoist-react/pull/1782
> Example of setting dimensions on DockViewModel.

- client-app/src/desktop/AppModel.js
- client-app/src/desktop/tabs/other/OtherTab.js
- client-app/src/desktop/tabs/other/PinPadPanel.js
- client-app/src/desktop/tabs/other/PinPadPanel.scss
See Hoist PR: https://github.com/xh/hoist-react/pull/1930
> Add desktop pinpad example

- client-app/src/apps/app.js
- client-app/src/apps/fileManager.js
- client-app/src/apps/mobile.js
- client-app/src/apps/news.js
- client-app/src/apps/portfolio.js
- client-app/src/apps/recalls.js
- client-app/src/desktop/tabs/other/AppNotificationsPanel.js
Update Toolbox to IdleService changes.
See hoist-react PR: https://github.com/xh/hoist-react/pull/1946
See hoist-core PR: https://github.com/xh/hoist-core/pull/147
> IdleService changes

- client-app/package.json
- client-app/src/Bootstrap.js
- client-app/yarn.lock
See hoist-react PR: https://github.com/xh/hoist-react/pull/1965
> Upgrade to agGrid v23.1.1

- client-app/src/desktop/common/grid/SampleGridModel.js
Paired with Hoist React PR: https://github.com/xh/hoist-react/pull/2031
> Elided header tooltip

- client-app/src/desktop/tabs/forms/FormPanelModel.js
Relates to https://github.com/xh/hoist-react/pull/2014
> Use new validEmail constraint instead of async validEmail

- client-app/src/admin/tests/cube/CubeTestModel.js
- client-app/src/admin/tests/cube/dimensions/DimensionManager.js
- client-app/src/admin/tests/cube/dimensions/DimensionManagerModel.js
- client-app/src/desktop/common/grid/SampleTreeGrid.js
- client-app/src/desktop/common/grid/SampleTreeGridModel.js
- client-app/src/desktop/tabs/charts/GridTreeMapModel.js
- client-app/src/desktop/tabs/charts/GridTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanelModel.js
- client-app/src/examples/news/NewsPanel.js
- client-app/src/examples/news/NewsPanelModel.js
- client-app/src/examples/portfolio/PortfolioPanelModel.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
Please see hoist-react PR: https://github.com/xh/hoist-react/pull/2002
> FilterModel

- client-app/src/admin/tests/cube/LoadTimesModel.js
- client-app/src/admin/tests/cube/LoadTimesPanel.js
- client-app/src/admin/tests/cube/dimensions/DimensionManager.js
- client-app/src/admin/tests/cube/dimensions/DimensionManagerModel.js
This PR remedies breaking changes caused by https://github.com/xh/hoist-react/pull/2093
> Move hideHeaders from Grid prop to GridModel config

- client-app/src/admin/tests/cube/CubeTestModel.js
- client-app/src/admin/tests/grids/GridTestModel.js
- client-app/src/admin/tests/grids/GridTestPanel.js
- client-app/src/desktop/common/grid/SampleColumnGroupsGrid.js
- client-app/src/desktop/common/grid/SampleGridModel.js
- client-app/src/desktop/common/grid/SampleTreeGridModel.js
- client-app/src/desktop/tabs/containers/dash/widgets/GridWidget.js
- client-app/src/examples/portfolio/GridPanelModel.js
- client-app/src/examples/portfolio/detail/OrdersPanelModel.js
- client-app/src/examples/recalls/RecallsPanelModel.js
- client-app/src/mobile/grids/GridPageModel.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
This PR remedies breaking changes caused by: https://github.com/xh/hoist-react/pull/2086
> Replace enableColChooser with colChooserModel in grid model configs

- client-app/src/desktop/tabs/containers/dash/DashContainerPanel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2137
> Improve DashContainer state documentation and example

- client-app/src/desktop/tabs/home/HomeTabModel.js
Linked to https://github.com/xh/hoist-react/issues/2145
Requires https://github.com/xh/hoist-react/pull/2149
> Add Restore Dash Defaults menu item to home tab

- client-app/src/admin/roadmap/RoadmapTab.js
- client-app/src/admin/tests/TestsTab.js
- client-app/src/admin/wip/WipTab.js
- client-app/src/desktop/App.scss
- client-app/src/desktop/AppModel.js
- client-app/src/desktop/tabs/charts/ChartsTab.js
- client-app/src/desktop/tabs/containers/ContainersTab.js
- client-app/src/desktop/tabs/containers/TabPanelContainerPanel.js
- client-app/src/desktop/tabs/forms/FormsTab.js
- client-app/src/desktop/tabs/grids/GridsTab.js
- client-app/src/desktop/tabs/other/OtherTab.js
- client-app/src/desktop/tabs/panels/PanelsTab.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2162
> Tab Switcher Enhancements

- client-app/package.json
- client-app/src/desktop/common/grid/options/AgGridOptions.js
- client-app/src/desktop/common/grid/options/AgGridOptionsPanel.js
- client-app/yarn.lock
paired with HR PR: https://github.com/xh/hoist-react/pull/2211
> Ag grid24 + plus ag-grid wrapper demo state save/load buttons.

- client-app/src/desktop/common/grid/SampleTreeGrid.js
- client-app/src/desktop/common/grid/SampleTreeGridModel.js
- client-app/src/examples/portfolio/GridPanel.js
- client-app/src/examples/portfolio/PortfolioPanelModel.js
- client-app/src/mobile/treegrids/TreeGridPage.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2200
> Use GroupingChooser component

- client-app/src/admin/tests/grids/GridTestModel.js
- client-app/src/admin/tests/grids/GridTestPanel.js
Test for https://github.com/xh/hoist-react/pull/2225
> Add controls for testing new `GridModel.lockColumnGroups` config

- client-app/src/mobile/treegrids/TreeGridPage.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2269
> Add ExpandCollapseButton to TreeGridPage

- client-app/src/mobile/AppModel.js
- client-app/src/mobile/home/HomePage.js
- client-app/src/mobile/popover/PopoverPage.js
- client-app/src/mobile/popover/PopoverPage.scss
See hoist-react PR: https://github.com/xh/hoist-react/pull/2271
> Add Popover examples to mobile

- client-app/src/desktop/tabs/panels/ToolbarPanel.js
- client-app/src/desktop/tabs/panels/ToolbarPanelModel.js
See issue: https://github.com/xh/hoist-react/issues/2333
See hoist-react PR: https://github.com/xh/hoist-react/pull/2347
> Add `compact` prop to Toolbar

- client-app/src/desktop/tabs/other/ErrorMessagePanel.js
Corresponding HR PR: https://github.com/xh/hoist-react/pull/2331
> Tweak to ErrorMessagePanel, to work with errorMessage that supports null/undefined error prop.

- client-app/src/mobile/form/FormPage.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2281
> Add an example menu title to Toolbox

- client-app/src/desktop/tabs/charts/GridTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SimpleTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanel.js
Add configuration controls to TreeMap examples.
See hoist-react PR: https://github.com/xh/hoist-react/pull/2364
> TreeMap Enhancements

- client-app/src/desktop/tabs/other/AppNotificationsPanel.js
- client-app/src/desktop/tabs/other/ErrorMessagePanel.js
- client-app/src/desktop/tabs/other/PopupsPanel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2386
> Add shared AppBanner

- client-app/src/mobile/AppModel.js
Links issue https://github.com/xh/hoist-react/issues/2148
Requires Hoist PR: https://github.com/xh/hoist-react/pull/2150
> Add navigation tracking to mobile app

- client-app/src/admin/tests/cube/dimensions/DimensionManager.js
- client-app/src/admin/tests/cube/dimensions/DimensionManagerModel.js
- client-app/src/desktop/tabs/charts/GridTreeMapModel.js
- client-app/src/desktop/tabs/charts/GridTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanelModel.js
For Hoist React issue https://github.com/xh/hoist-react/issues/2370.
Pair with HoistReact PR: https://github.com/xh/hoist-react/pull/2430
> Replace deprecated DimensionChooser with GroupingChooser

- client-app/src/admin/tests/storeEditing/StoreEditingPanelModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2439
> Add InlineSelectEditor examples to StoreEditingPanelModel

- client-app/src/admin/tests/storeEditing/StoreEditingPanel.js
- client-app/src/admin/tests/storeEditing/StoreEditingPanelModel.js
- client-app/src/desktop/tabs/forms/FormPanelModel.js
- client-app/src/desktop/tabs/forms/ToolbarFormPanelModel.js
- client-app/src/desktop/tabs/other/PopupsPanel.js
- client-app/src/mobile/AppModel.js
- client-app/src/mobile/form/FormPageModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2453
> Inline Editing Validation

- client-app/src/examples/todo/TodoPanelModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2471
> Refresh row height on data change when autoheight = true

- client-app/src/desktop/tabs/home/widgets/activity/ActivityWidget.js
- client-app/src/desktop/tabs/home/widgets/activity/ActivityWidgetModel.js
- client-app/src/examples/news/NewsPanel.js
- client-app/src/examples/news/NewsPanelModel.js
- client-app/src/examples/todo/TodoPanel.js
- client-app/src/examples/todo/TodoPanelModel.js
- client-app/src/mobile/grids/GridPage.js
- client-app/src/mobile/grids/GridPageModel.js
- client-app/src/mobile/treegrids/TreeGridPage.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
See matching hoist-react PR.
Also, discussed with Lee, we will double check the mobile grids after merge.
> Grid cmp callbacks

- client-app/src/desktop/tabs/containers/TileFrameContainerPanel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2482
> TileFrame V2

- client-app/src/mobile/charts/ChartPageModel.js
Fixes date formatting in mobile chart tooltip
- tooltip formatting now matches desktop version of this chart
> Mobile chart tooltip formatting

- CHANGELOG.md
- client-app/src/desktop/AppModel.js
- client-app/src/desktop/tabs/other/OtherTab.js
- client-app/src/desktop/tabs/other/PlaceholderPanel.js
See https://github.com/xh/hoist-react/pull/2525 - this is a pre-req for this example to get the icon styling mentioned in the wrapper description text.
> Add Other > Placeholder example

- client-app/src/admin/tests/grids/GridTestModel.js
- client-app/src/desktop/common/grid/SampleTreeGridModel.js
- client-app/src/desktop/tabs/grids/TreeGridPanel.js
- client-app/src/mobile/treegrids/TreeGridPage.js
> Tree grid header expand/collapse all icon defaults to enabled

- client-app/src/desktop/tabs/grids/InlineEditingPanel.js
- client-app/src/desktop/tabs/grids/InlineEditingPanelModel.js
Pair with Hoist React PR: https://github.com/xh/hoist-react/pull/2554
> Demo GridModel.clicksToEdit

- client-app/src/desktop/tabs/grids/InlineEditingPanel.js
- client-app/src/desktop/tabs/grids/InlineEditingPanel.scss
- client-app/src/desktop/tabs/grids/InlineEditingPanelModel.js
+ Fixup custom editable cell color in dark mode.
+ For consideration with https://github.com/xh/hoist-react/pull/2561
> Demo public GridModel APIs to stop/start editing

- client-app/src/desktop/tabs/forms/ToolbarFormPanel.js
Cleaned up while working on adding readonlyRenderer as new fieldDefault: https://github.com/xh/hoist-react/pull/2565
> Utilize Form fieldDefaults

- client-app/src/desktop/tabs/containers/tab/tabs/TabStateExample.js
- client-app/src/mobile/App.js
See matching hoist-react PR.
Position prop has been removed from component.
> Badge component has compact prop

- client-app/src/examples/todo/TodoPanelModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2602
> Icon factories should take an intent config

- client-app/src/desktop/tabs/charts/GridTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SimpleTreeMapPanel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2603
> Add `theme` controls to TreeMap examples

- client-app/src/admin/tests/columnFilters/store/StoreColumnFilterPanelModel.js
- client-app/src/admin/tests/columnFilters/view/ViewColumnFilterPanelModel.js
- client-app/src/admin/tests/cube/CubeTestModel.js
- client-app/src/desktop/AppModel.js
- client-app/src/desktop/AppOptions.js
- client-app/src/desktop/common/grid/SampleColumnGroupsGrid.js
- client-app/src/desktop/common/grid/SampleGridModel.js
- client-app/src/desktop/common/grid/SampleTreeGridModel.js
- client-app/src/desktop/tabs/charts/GridTreeMapModel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanelModel.js
- client-app/src/desktop/tabs/containers/dash/widgets/GridWidget.js
- client-app/src/desktop/tabs/grids/AgGridViewModel.js
- client-app/src/examples/filemanager/AppModel.js
- client-app/src/examples/news/AppModel.js
- client-app/src/examples/portfolio/AppModel.js
- client-app/src/examples/portfolio/GridPanelModel.js
- client-app/src/examples/portfolio/detail/OrdersPanelModel.js
- client-app/src/examples/todo/TodoPanelModel.js
- client-app/src/mobile/AppModel.js
Use built-in XH.sizingMode throughout Toolbox
See hoist-react PR: xh/hoist-react#2593
See hoist-core PR: https://github.com/xh/hoist-core/pull/205
> Build in support for sizingMode to Hoist

- CHANGELOG.md
- client-app/src/mobile/grids/GridPageModel.js
- client-app/src/mobile/treegrids/TreeGridPage.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
- client-app/yarn.lock
See hoist-react PR: https://github.com/xh/hoist-react/pull/2701
> Use long-press to drilldown into parent rows

- client-app/src/core/columns/Demographics.js
- client-app/src/core/columns/General.js
- client-app/src/core/columns/Orders.js
- client-app/src/core/columns/Positions.js
- client-app/src/core/columns/Sales.js
- client-app/src/core/columns/Trades.js
- client-app/src/core/columns/index.js
- client-app/src/desktop/common/grid/SampleColumnGroupsGrid.js
- client-app/src/desktop/common/grid/SampleGridModel.js
- client-app/src/desktop/common/grid/SampleTreeGridModel.js
- client-app/src/desktop/tabs/charts/GridTreeMapModel.js
- client-app/src/desktop/tabs/charts/SimpleTreeMapModel.js
- client-app/src/desktop/tabs/charts/SplitTreeMapPanelModel.js
- client-app/src/desktop/tabs/containers/dash/widgets/GridWidget.js
- client-app/src/desktop/tabs/grids/ColumnFilteringPanelModel.js
- client-app/src/desktop/tabs/grids/DataViewPanel.js
- client-app/src/desktop/tabs/grids/RestGridPanel.js
- client-app/src/desktop/tabs/home/widgets/roadmap/RoadmapModel.js
- client-app/src/examples/contact/DirectoryPanelModel.js
- client-app/src/examples/news/NewsPanelModel.js
- client-app/src/examples/portfolio/GridPanelModel.js
- client-app/src/examples/portfolio/PortfolioPanelModel.js
- client-app/src/examples/portfolio/detail/OrdersPanelModel.js
- client-app/src/examples/recalls/RecallsPanelModel.js
- client-app/src/examples/todo/TodoPanelModel.js
- client-app/src/mobile/dataview/DataViewPageModel.js
- client-app/src/mobile/grids/GridPageModel.js
- client-app/src/mobile/treegrids/TreeGridPageModel.js
+ Specify explicit field types throughout Toolbox
+ Create library of reusable columns, which define their field inline
See hoist-react PR: https://github.com/xh/hoist-react/pull/2721
> Specify explicit field types in Toolbox

- client-app/src/desktop/App.js
See matching hoist-react PR: https://github.com/xh/hoist-react/pull/2784
> Build refresh app data hotkey into hoist

- CHANGELOG.md
- client-app/src/mobile/AppModel.js
- client-app/src/mobile/buttons/ButtonPage.js
- client-app/src/mobile/buttons/ButtonPage.scss
- client-app/src/mobile/buttons/ButtonPageModel.js
- client-app/src/mobile/containers/ToolbarPage.js
- client-app/src/mobile/home/HomePage.js
- client-app/src/mobile/panels/PanelPage.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2792
> Harmonize mobile button props with desktop

- client-app/src/admin/tests/columnFilters/store/StoreColumnFilterPanelModel.js
- client-app/src/core/columns/Trades.js
- client-app/src/desktop/tabs/grids/RestGridPanel.js
+ Rename ExportFormat > ExcelFormat
+ Rename Column.exportFormat > Column.excelFormat
See HR PR: https://github.com/xh/hoist-react/pull/2848
> ExcelFormat

- client-app/src/desktop/tabs/home/widgets/activity/ActivityWidgetModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2846
> FilterChooserFieldSpec.enableValues

- build.gradle
- gradle.properties
- grails-app/conf/runtime.groovy
More verifiably enable/disable Spring developer tools
+ https://stackoverflow.com/questions/59252470/gradle-spring-boot-devtools-developmentonly-and-runtimeclasspath
> Improvements to dev-time support

- client-app/src/desktop/tabs/forms/InputsPanel.js
- client-app/src/desktop/tabs/forms/InputsPanelModel.js
- client-app/src/mobile/form/FormPage.js
- client-app/src/mobile/form/FormPageModel.js
Examples of new `scaleFactor` prop on `NumberInput`
> Add `scaleFactor` prop to NumberInput

- client-app/src/desktop/common/grid/SampleColumnGroupsGrid.js
- client-app/src/desktop/tabs/home/widgets/activity/ActivityWidget.js
- client-app/src/desktop/tabs/home/widgets/activity/ActivityWidgetModel.js
See issue: https://github.com/xh/hoist-react/issues/2872
> Fix default groupBy in Grouped Columns Grid and ActivityWidget

- CHANGELOG.md
- client-app/src/mobile/App.scss
Further information in issue:
https://github.com/xh/toolbox/issues/495
> Auth0 full screen fix

- client-app/src/examples/contact/DirectoryPanel.scss
- client-app/src/examples/contact/DirectoryPanelModel.js
- client-app/src/examples/contact/cmp/FavoriteButton.js
- client-app/src/examples/contact/cmp/FavoriteButton.scss
- client-app/src/examples/contact/cmp/TileView.scss
- client-app/src/examples/contact/details/DetailsPanel.js
- client-app/src/examples/contact/details/DetailsPanelModel.js
- client-app/src/examples/contact/svc/ContactService.js
> Fix favorites feature in Contact app

- client-app/src/desktop/common/grid/SampleGridModel.js
See hoist-react PR: https://github.com/xh/hoist-react/pull/2904
> Add example usage of GridModel.restoreDefaultsFn()

- client-app/src/desktop/tabs/mobile/MobileTab.scss
> Fix squished images in Mobile tab on desktop

- client-app/src/desktop/tabs/containers/tab/tabs/CustomExample.js
> Fix broken custom tab switcher example

- client-app/src/core/columns/Demographics.js
The full name column would not copy to the clipboard as there is no field for it.
> Add exportValue to provide value for clipboard

- client-app/src/mobile/form/FormPage.js
See https://github.com/xh/hoist-react/pull/3024
> Enable clear on mobile form example's textInput

- client-app/src/desktop/tabs/layout/dashcanvas/DashCanvasPanel.js
- client-app/src/desktop/tabs/layout/widgets/ChartWidget.js
- client-app/src/desktop/tabs/layout/widgets/ChartWidget.scss
- client-app/src/desktop/tabs/layout/widgets/GridWidget.js
see https://github.com/xh/hoist-react/pull/3028
> Add DashCanvasViewModel support for extraMenuItems and headerItems

- CHANGELOG.md
- client-app/package.json
- client-app/src/Bootstrap.js
- client-app/src/core/columns/Orders.js
- client-app/src/core/svc/PortfolioService.js
- client-app/src/examples/portfolio/detail/OrdersPanelModel.js
- client-app/src/examples/portfolio/detail/charts/ChartsPanel.js
- client-app/yarn.lock
- grails-app/controllers/io/xh/toolbox/portfolio/PortfolioController.groovy
- grails-app/services/io/xh/toolbox/portfolio/PortfolioService.groovy
`LineChart.js` is no longer used.  Thought about deleting it, but I wonder if it still might be a valuable HighCharts example?
> Add grid `sparklines` to Portfolio example

- grails-app/controllers/io/xh/toolbox/portfolio/PortfolioController.groovy
Found this in the Grails docs for handling parameter type conversion to simplify this a bit:
http://docs.grails.org/latest/guide/single.html#typeConverters
> Minor refactor of PortfolioController.closingPriceHistory

- client-app/src/admin/roadmap/ProjectRestPanel.ts
Gave codeInput a height so it is not 100% of 0px
> Add Typescript type

- client-app/src/admin/roadmap/ProjectRestPanel.ts
> Height added to Github links CodeInput

- client-app/src/admin/AppModel.ts
- client-app/src/admin/tests/grids/GridTestModel.ts
- client-app/src/desktop/common/Wrapper.ts
- client-app/src/desktop/tabs/panels/MaskPanel.tsx
- client-app/src/examples/contact/AppModel.ts
- client-app/src/examples/contact/DirectoryPanelModel.ts
- client-app/src/examples/contact/svc/ContactService.ts
- client-app/src/examples/filemanager/AppModel.ts
- client-app/src/examples/portfolio/AppModel.ts
- client-app/src/examples/portfolio/detail/charts/ChartsPanelModel.ts
- client-app/src/examples/portfolio/detail/charts/LineChart.ts
- client-app/src/examples/portfolio/detail/charts/OHLCChart.ts
- client-app/src/examples/recalls/RecallsPanelModel.ts
- client-app/src/examples/todo/AppModel.ts
- client-app/src/examples/todo/TodoPanelModel.ts
- client-app/src/mobile/grids/GridDetailPage.ts
- client-app/src/mobile/treegrids/TreeGridDetailPage.ts
- client-app/tsconfig.json
Set `"noImplicitOverride": true` in `tsconfig.json`. Ensure all overridden properties and methods have the `override` keyword.
Closes #638
> Fix Implicit Overriding

- client-app/src/desktop/tabs/forms/InputsPanel.tsx
See hoist-react PR: https://github.com/xh/hoist-react/pull/3296
> Remove fill prop usages from Toolbox

- client-app/src/examples/portfolio/PortfolioPanelModel.ts
Wait until the WebSocket connection is established before getting a live positions session in the portfolio example grid. 
After five seconds without a connection, continue loading the grid without WebSockets. 
If the WebSocket becomes connected in the future, doLoadAsync will be run, reloading the grid with a WebSocket connection for live position updates.
Resolve #627 
Co-dev/CR Lee
> Wait for WebSocket connection in portfolio example

- client-app/src/desktop/tabs/other/PopupsPanel.tsx
- client-app/src/mobile/popups/PopupsPage.ts
For https://github.com/xh/hoist-react/pull/3344.
> Added generic type to `XH.promise()`

- client-app/src/examples/portfolio/GridPanel.ts
- client-app/src/examples/portfolio/GridPanelModel.ts
- client-app/src/examples/portfolio/detail/DetailPanel.ts
See hoist-react PR https://github.com/xh/hoist-react/pull/3478
> DRY with recently-added props Panel.collapsedTitle and Panel.collapsedIcon

- .gitignore
- client-app/tsconfig.json
- client-app/yarn.lock
+ Allow for distinct tsconfig options in HR vs. app-level. Relies on `composite: true` flag to be set in hoist-react tsconfig.json.
+ Re-order tsconfig options for clarity.
> Update tsconfig.json to ref hoist-react as composite build

- CHANGELOG.md
- grails-app/services/io/xh/toolbox/user/RoleService.groovy
Think this is very useful so we can track and test our UI enhancements to this important functionality within toolbox
> Config to support mock directory group lookups

- client-app/src/mobile/buttons/ButtonPage.ts
- client-app/src/mobile/form/FormPage.ts
- client-app/src/mobile/form/FormPageModel.ts
- client-app/src/mobile/grids/GridPage.ts
- client-app/src/mobile/grids/tree/TreeGridPage.ts
With https://github.com/xh/hoist-react/pull/3664
> Use new mobile `checkboxButton` component

- grails-app/services/io/xh/toolbox/admin/TestCacheService.groovy
- grails-app/services/io/xh/toolbox/admin/TestCachedValueService.groovy
- grails-app/services/io/xh/toolbox/admin/TestSerializationService.groovy
- grails-app/services/io/xh/toolbox/admin/TestUtils.groovy
- grails-app/services/io/xh/toolbox/app/NewsService.groovy
- grails-app/services/io/xh/toolbox/portfolio/PortfolioService.groovy
Please note new TestServices in io.xh.toolbox.admin
> CachedValue and related enhancements to multi-instance support

- client-app/src/admin/tests/viewmanager/ViewManagerTestModel.ts
- client-app/src/admin/tests/viewmanager/ViewManagerTestPanel.ts
Works with HR viewManagerFeaturesGS branch. Note - substantially commented out code in Admin test tab.
> Refactor View Manager state + general cleanup

- client-app/src/admin/tests/viewmanager/ViewManagerTestModel.ts
- client-app/src/admin/tests/viewmanager/ViewManagerTestPanel.ts
- client-app/src/examples/portfolio/AppModel.ts
+ support for Global label
+ remove autoSave
> Update to latest view manager

- client-app/src/admin/tests/fetch/FetchApiTestPanel.ts
- client-app/src/desktop/tabs/charts/GridTreeMapModel.ts
- client-app/src/desktop/tabs/charts/GridTreeMapPanel.ts
- client-app/src/desktop/tabs/charts/SimpleTreeMapModel.ts
- client-app/src/desktop/tabs/charts/SimpleTreeMapPanel.tsx
- client-app/src/desktop/tabs/charts/SplitTreeMapPanel.ts
- client-app/src/desktop/tabs/charts/SplitTreeMapPanelModel.ts
- client-app/src/desktop/tabs/other/ErrorMessagePanel.tsx
- client-app/src/desktop/tabs/panels/LoadingIndicatorPanel.tsx
- client-app/src/desktop/tabs/panels/MaskPanel.tsx
- client-app/src/examples/portfolio/detail/charts/LineChart.ts
- client-app/src/examples/portfolio/detail/charts/OHLCChart.ts
- client-app/src/examples/portfolio/map/PositionsMap.ts
- client-app/src/examples/portfolio/map/PositionsMapModel.ts
- client-app/src/mobile/AppModel.ts
- client-app/src/mobile/grids/tree/TreeGridDetailPage.ts
- client-app/src/mobile/home/HomePage.ts
- client-app/src/mobile/treemap/TreeMapPage.ts
- client-app/src/mobile/treemap/TreeMapPageModel.ts
See issue: https://github.com/xh/hoist-react/issues/3818
See Hoist React PR: https://github.com/xh/hoist-react/pull/3866
> Make TreeMap cross-platform + mobile example

- client-app/src/examples/contact/mobile/AppModel.ts
- client-app/src/examples/contact/mobile/DirectoryPanelModel.ts
- client-app/src/examples/contact/mobile/details/DetailsPanelModel.ts
+ Use AppModel.contacts as the sole observable source of truth
+ Grid records observe changes to AppModel.contacts
+ Detail panel observes changes to AppModel.contacts
> Suggested adjustments to mobile contact app
